[package]
name = "bgn"
authors = ["Florian Wilkens <gh@1wilkens.org>"]
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
reqwest = { version = "0.12", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
tera = "1.0"
